accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
init:
  # see /root/.duality/config/config.toml
  config:
    consensus:
      # slow down block creation
      # why? the default 1 block per second is quite fast even for development purposes
      # it may be cause some CPU stress and can quickly expand a Docker container and the OS Docker.raw file
      # this used space can be reclaimed by removing the Docker container and recreating it (starting a new chain)
      timeout_commit: 7s # default 1s

      # the following settings should work but don't, see issues:
      # - https://github.com/ignite/cli/issues/376#issuecomment-828858154
      # - https://github.com/ignite/cli/issues/419#issuecomment-738875416
      # - https://github.com/tendermint/tendermint/issues/2920
      # - https://github.com/tendermint/tendermint/issues/5911
      create_empty_blocks: false # default is true
      create_empty_blocks_interval: 7s # default is 0s
