version: "3"

# to run testnet for the first time, or first time since changes have been made:
#   $ docker-compose build
#   $ docker-compose up
#   or
#   $ docker-compose up --build
# to run built testnet again
#   $ docker-compose up
# to remove testnet
#   $ docker-compose down

services:

  # to open a terminal inside the test node use the command:
  #   $ docker-compose exec dualitytester /bin/bash
  # from there you can use commands with the test keys such as when sending a Msg to dualitynode0:
  #   $ dualityd tx dex single-deposit --from alice --node tcp://dualitynode0:26657 [...args]
  # and an example with arguments (note that the token amounts are specified in tokens not Î¼tokens):
  #   $ dualityd tx dex single-deposit --from alice --node tcp://dualitynode0:26657 token stake 2000 0.01 0.0000000000000001 0.0000000000000001 cosmos1ja2nyfhyyyxam5qhll8g7wwy5km0stuwrl949a
  # you can check that this transaction has synced across the nodes by querying another node before and after the Msg
  #   $ dualityd query tx --node tcp://dualitynode1:26657 [txhash]
  # you can also add the test accounts (created in Dockerfile-testnets) into your Keplr wallet
  # using the mnemonics generated (printed in dualitytester container startup command)
  # although using this directly in the browser appears to cause a signing error(?),
  # you can use Keplr to transfer tokens to another permenantly setup wallet and use that to make Msgs against the testnet.
  dualitytester:
    container_name: dualitytester
    build:
      context: .
      dockerfile: Dockerfile-testnet
      target: testnode
    command: >
      /bin/sh -c '
        # check if we can get information from the testnet
        bash /root/.duality/scripts/check_testnet_status.sh

        # wait a bit to prove we are catching up
        echo "waiting for testnet to progress in height a little so we can make requests as alice or bob";
        # if height is not sufficient this error may appear: Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account [address] not found: key not found
        #(wait at least one block height)
        sleep 10;

        # complete stress test suite
        echo "running stress test suite...";
        bash /root/.duality/scripts/stress_tests.sh
        echo "finished stress test suite...";

        # wait a bit to prove we are catching up
        echo "waiting for testnet to progress in height a little...";
        sleep 10;

        # start as full node
        echo "starting as full node";
        dualityd start --log_level $LOG_LEVEL --moniker testnode & \

        # wait a bit more to prove we are transitioning to a full node
        sleep 10;

        # todo: maybe add a `bash /root/.duality/scripts/check_fullnode_status.sh
        # to check is the node is known by its peers

        # request to be a validator
        echo "requesting test full node to become a validator";
        dualityd tx staking create-validator \
          --node tcp://dualitynode1:26657 \
          --moniker testnode \
          --node-id `dualityd tendermint show-node-id` \
          --pubkey `dualityd tendermint show-validator` \
          --commission-rate="1.0" \
          --commission-max-rate="1.0" \
          --commission-max-change-rate="1.0" \
          --min-self-delegation="1" \
          --gas="auto" \
          --amount 100000000stake \
          --fees 1000token \
          --from alice \
          -y

        bash /root/.duality/scripts/check_validator_status.sh
      '
    environment:
      - DEBUG=1
      - LOG_LEVEL=${LOG_LEVEL:-info}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26646-26647:26656-26657"
      - "1316:1317"
      - "9089:9090"
      - "2344:2345"
    volumes:
      - go-modules:/go/pkg/mod
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  dualitynode0:
    container_name: dualitynode0
    build:
      context: .
      dockerfile: Dockerfile-testnet
      args:
        NODE_ID: 0
    command: dualityd --home /testnet/dualityd start --moniker "node0" --log_level $LOG_LEVEL
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-simd.log}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    volumes:
      - go-modules:/go/pkg/mod
    networks:
      localnet:
        ipv4_address: 192.168.10.10

  dualitynode1:
    container_name: dualitynode1
    build:
      context: .
      dockerfile: Dockerfile-testnet
      args:
        NODE_ID: 1
    command: dualityd --home /testnet/dualityd start --moniker "node1" --log_level $LOG_LEVEL
    environment:
      - DEBUG=0
      - ID=1
      - LOG=${LOG:-simd.log}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
    volumes:
      - go-modules:/go/pkg/mod
    networks:
      localnet:
        ipv4_address: 192.168.10.11

  dualitynode2:
    container_name: dualitynode2
    build:
      context: .
      dockerfile: Dockerfile-testnet
      args:
        NODE_ID: 2
    command: dualityd --home /testnet/dualityd start --moniker "node2" --log_level $LOG_LEVEL
    environment:
      - DEBUG=0
      - ID=2
      - LOG=${LOG:-simd.log}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
      - "2347:2345"
    volumes:
      - go-modules:/go/pkg/mod
    networks:
      localnet:
        ipv4_address: 192.168.10.12

  dualitynode3:
    container_name: dualitynode3
    build:
      context: .
      dockerfile: Dockerfile-testnet
      args:
        NODE_ID: 3
    command: dualityd --home /testnet/dualityd start --moniker "node3" --log_level $LOG_LEVEL
    environment:
      - DEBUG=0
      - ID=3
      - LOG=${LOG:-simd.log}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
      - "2348:2345"
    volumes:
      - go-modules:/go/pkg/mod
    networks:
      localnet:
        ipv4_address: 192.168.10.13

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25

# this Docker volume space can be reclaimed using:
#   $ docker volume rm go-modules
volumes:
  go-modules: # Cached Go module dependencies are stored here
