version: "3.8"
services:
  genesis-node:
    image: 137158674376.dkr.ecr.us-west-2.amazonaws.com/duality:${TAG:-latest}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 8192M
    environment:
      - MODE=new
      - NODE_MONIKER=genesis-node
  follower-node:
    image: 137158674376.dkr.ecr.us-west-2.amazonaws.com/duality:${TAG:-latest}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 8192M
    # Only expose ports on follower node. This allows us to check network connectivity between nodes
    ports:
      #RPC
      - target: 26657
        x-aws-protocol: http
      #API
      - target: 1317
        x-aws-protocol: http
    healthcheck:
       test: ["CMD", "curl", "http://localhost:26657/health"]
    environment:
      - MODE=fullnode
      - RPC_ADDRESS=http://genesis-node:26657
      - NODE_MONIKER=follower-node
    depends_on:
     - genesis-node
