version: "3"

# to run testnet for the first time, or first time since changes have been made:
#   $ docker-compose build
#   $ docker-compose up
#   or
#   $ docker-compose up --build
# to run built testnet again
#   $ docker-compose up
# to remove testnet
#   $ docker-compose down

services:
  dualitynode0:
    container_name: dualitynode0
    build:
      context: .
      dockerfile: Dockerfile-testnet
      args:
        NODE_ID: 0
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-simd.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  dualitynode1:
    container_name: dualitynode1
    build:
      context: .
      dockerfile: Dockerfile-testnet
      args:
        NODE_ID: 1
    environment:
      - DEBUG=0
      - ID=1
      - LOG=${LOG:-simd.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  dualitynode2:
    container_name: dualitynode2
    build:
      context: .
      dockerfile: Dockerfile-testnet
      args:
        NODE_ID: 2
    environment:
      - DEBUG=0
      - ID=2
      - LOG=${LOG:-simd.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
      - "2347:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  dualitynode3:
    container_name: dualitynode3
    build:
      context: .
      dockerfile: Dockerfile-testnet
      args:
        NODE_ID: 3
    environment:
      - DEBUG=0
      - ID=3
      - LOG=${LOG:-simd.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
      - "2348:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25
