version: "3"

# to run testnet for the first time, or first time since changes have been made:
#   $ docker-compose build
#   $ docker-compose up
#   or
#   $ docker-compose up --build
# to run built testnet again
#   $ docker-compose up
# to remove testnet
#   $ docker-compose down

# one-liner to bring everything up and down again:
#   $ docker-compose up --build --abort-on-container-exit || true && docker-compose down

services:

  # to open a terminal inside the test node use the command:
  #   $ docker-compose exec dualitytester /bin/bash
  # from there you can use commands with the test keys such as when sending a Msg to dualitynode0:
  #   $ dualityd tx dex single-deposit --from alice --node tcp://dualitynode0:26657 [...args]
  # and an example with arguments (note that the token amounts are specified in tokens not Î¼tokens):
  #   $ dualityd tx dex single-deposit --from alice --node tcp://dualitynode0:26657 token stake 2000 0.01 0.0000000000000001 0.0000000000000001 cosmos1ja2nyfhyyyxam5qhll8g7wwy5km0stuwrl949a
  # you can check that this transaction has synced across the nodes by querying another node before and after the Msg
  #   $ dualityd query tx --node tcp://dualitynode1:26657 [txhash]
  # you can also override the test accounts (using MNEMONIC or MNEMONICS) passed in here
  dualitytester:
    container_name: dualitytester
    build:
      context: .
      target: testnet-env
      args:
        NETWORK: duality-testnet-1
    command: >
      /bin/bash -c '
        #!/bin/bash
        set -e

        # check if we can get information from the testnet
        bash /root/.duality/scripts/check_testnet_status.sh

        # wait a bit to prove we are catching up
        echo "waiting for testnet to progress in height a little so we can make requests as alice or bob";
        # if height is not sufficient this error may appear: Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account [address] not found: key not found
        #(wait at least one block height)
        sleep 10;

        # complete stress test suite
        echo "running stress test suite...";
        bash /root/.duality/scripts/wait_for_tests_to_finish.sh
        echo "finished stress test suite...";

        # wait a bit to prove we are catching up
        echo "waiting for testnet to progress in height a little...";
        sleep 10;

        # start as full node
        KEEP_RUNNING=false sh ./scripts/startup.sh

        # wait a bit more to prove we are transitioning to a full node
        sleep 10;

        # todo: maybe add a `bash /root/.duality/scripts/check_fullnode_status.sh
        # to check is the node is known by its peers

        # todo: add validator startup check

        # # request to be a validator
        # echo "requesting test full node to become a validator";
        # dualityd tx staking create-validator \
        #   --node tcp://dualitynode1:26657 \
        #   --moniker testnode \
        #   --node-id `dualityd tendermint show-node-id` \
        #   --pubkey `dualityd tendermint show-validator` \
        #   --commission-rate="1.0" \
        #   --commission-max-rate="1.0" \
        #   --commission-max-change-rate="1.0" \
        #   --min-self-delegation="1" \
        #   --gas="auto" \
        #   --amount 100000000stake \
        #   --fees 1000token \
        #   --from alice \
        #   -y \
        #   --output json \
        #   | echo "validator exit code: $$(jq -r .code)"

        # bash /root/.duality/scripts/check_validator_status.sh
      '
    environment:
      - DEBUG=1
      - NODE_MONIKER=tester
      - MODE=fullnode
      - RPC_ADDRESS=http://192.168.10.100:26657
      - MNEMONIC=
          absorb entire pelican ride economy about slide pig fruit miss just fit kit moon away grocery deliver sense secret galaxy frequent panel lab say
      - LOG_LEVEL=${LOG_LEVEL:-warn}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26646-26647:26656-26657"
      - "1316:1317"
      - "9089:9090"
      - "2344:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  dualityleader:
    container_name: dualityleader
    build:
      context: .
      target: testnet-env
      args:
        NETWORK: duality-testnet-1
    environment:
      - DEBUG=1
      - NODE_MONIKER=leader
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - MODE=new
      - FAUCET=tail raccoon real chaos item lift pretty slice normal come target rack public design concert vintage main word evolve dog denial bomb swarm tortoise
      - MNEMONICS=
          life remember forward tiny acoustic trumpet viable alcohol shadow thank dress intact metal brain marble poverty fashion segment cheap course improve fancy material shoot;
          rain pottery tongue end fortune normal clown uphold half explain tumble cherry any acid arrange harbor limit cradle finish armor addict artist combine shine;
          dilemma neck brief siege body spray swap never clown spice system element aware monster scout dentist vessel jewel frost bargain fossil put lens talent;
          benefit crater fitness border slow rack void owner tag round mobile couch wool cheap such scale summer diary electric obey check pitch fresh muscle;
          absorb entire pelican ride economy about slide pig fruit miss just fit kit moon away grocery deliver sense secret galaxy frequent panel lab say;
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26636-26637:26656-26657"
      - "1315:1317"
      - "9088:9090"
      - "2343:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.100

  dualitynode0:
    container_name: dualitynode0
    build:
      context: .
      target: testnet-env
      args:
        NETWORK: duality-testnet-1
        NODE_ID: 0
    command: sh /root/.duality/scripts/start-testnet.sh
    environment:
      - DEBUG=1
      - NODE_MONIKER=node0
      - MODE=fullnode
      - RPC_ADDRESS=http://192.168.10.100:26657
      - ID=0
      - LOG=${LOG:-simd.log}
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - FAUCET=tail raccoon real chaos item lift pretty slice normal come target rack public design concert vintage main word evolve dog denial bomb swarm tortoise
      - MNEMONIC=
          life remember forward tiny acoustic trumpet viable alcohol shadow thank dress intact metal brain marble poverty fashion segment cheap course improve fancy material shoot
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.10

  dualitynode1:
    container_name: dualitynode1
    build:
      context: .
      target: testnet-env
      args:
        NETWORK: duality-testnet-1
        NODE_ID: 1
    command: sh /root/.duality/scripts/start-testnet.sh
    environment:
      - DEBUG=0
      - NODE_MONIKER=node1
      - MODE=fullnode
      - RPC_ADDRESS=http://192.168.10.100:26657
      - ID=1
      - LOG=${LOG:-simd.log}
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - FAUCET=tail raccoon real chaos item lift pretty slice normal come target rack public design concert vintage main word evolve dog denial bomb swarm tortoise
      - MNEMONIC=
          rain pottery tongue end fortune normal clown uphold half explain tumble cherry any acid arrange harbor limit cradle finish armor addict artist combine shine
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.11

  dualitynode2:
    container_name: dualitynode2
    build:
      context: .
      target: testnet-env
      args:
        NETWORK: duality-testnet-1
        NODE_ID: 2
    command: sh /root/.duality/scripts/start-testnet.sh
    environment:
      - DEBUG=0
      - NODE_MONIKER=node2
      - MODE=fullnode
      - RPC_ADDRESS=http://192.168.10.100:26657
      - ID=2
      - LOG=${LOG:-simd.log}
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - FAUCET=tail raccoon real chaos item lift pretty slice normal come target rack public design concert vintage main word evolve dog denial bomb swarm tortoise
      - MNEMONIC=
          dilemma neck brief siege body spray swap never clown spice system element aware monster scout dentist vessel jewel frost bargain fossil put lens talent
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
      - "2347:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.12

  dualitynode3:
    container_name: dualitynode3
    build:
      context: .
      target: testnet-env
      args:
        NETWORK: duality-testnet-1
        NODE_ID: 3
    command: sh /root/.duality/scripts/start-testnet.sh
    environment:
      - DEBUG=0
      - NODE_MONIKER=node3
      - MODE=fullnode
      - RPC_ADDRESS=http://192.168.10.100:26657
      - ID=3
      - LOG=${LOG:-simd.log}
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - FAUCET=tail raccoon real chaos item lift pretty slice normal come target rack public design concert vintage main word evolve dog denial bomb swarm tortoise
      - MNEMONIC=
          benefit crater fitness border slow rack void owner tag round mobile couch wool cheap such scale summer diary electric obey check pitch fresh muscle
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
      - "2348:2345"
    networks:
      localnet:
        ipv4_address: 192.168.10.13

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25
