version: "3"

services:
  # to run as a single command:
  # docker-compose -f docker-compose.setup.yml run -it --rm init-files
  init-files:
    container_name: init-files
    image: interchainio/simapp:v0.45.4
    command: >
      simd testnet init-files \
        --v 4 \
        -o .testnets \
        --starting-ip-address 192.168.10.2 \
        --keyring-backend test \
        --chain-id duality \
        --node-daemon-home dualityd
    environment:
      - DEBUG=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./.testnets:/root/.testnets:Z
