# get testnet configurations
FROM interchainio/simapp:v0.45.4 as testnetconfig
# generate base chain testnet configurations /root/.testnet
RUN simd testnet init-files \
    --v 4 \
    -o .testnet \
    --starting-ip-address 192.168.10.2 \
    --keyring-backend test \
    --chain-id duality \
    --node-daemon-home dualityd

# [Choice] Go version (use -bullseye variants on local arm64/Apple Silicon): 1, 1.16, 1.17, 1-bullseye, 1.16-bullseye, 1.17-bullseye, 1-buster, 1.16-buster, 1.17-buster
FROM golang:1.18-bullseye

# install additional OS packages.
RUN apt update && \
    apt upgrade -y

RUN apt-get install -y \
    build-essential \
    ca-certificates \
    jq \
    curl

WORKDIR /usr/src

# Get Go dependencies
COPY go.mod ./go.mod
COPY go.sum ./go.sum
RUN go mod download

# Copy work files (but not Dockerfile: to avoid invalidating caches while developing)
COPY app ./app
COPY cmd ./cmd
COPY docs ./docs
COPY proto ./proto
COPY testutil ./testutil
COPY vue ./vue
COPY x ./x
COPY config.yml ./config.yml

# compile dualityd
RUN go install ./cmd/dualityd

# create duality chain config files
RUN dualityd init duality

# get testnet config files
ARG NODE_ID
COPY --from=testnetconfig /root/.testnet/node$NODE_ID /testnet/

# merge genesis files together:
# take initial state of "auth", "bank", and "genutil" (the genesis txs) from the testnets configuration only
RUN jq -s '.[0] * { app_state: { auth: .[1].app_state.auth, bank: .[1].app_state.bank, genutil: .[1].app_state.genutil } }' \
    /root/.duality/config/genesis.json /testnet/dualityd/config/genesis.json \
    > /root/combined-genesis.json
# overwrite genesis file that will be used
RUN cp /root/combined-genesis.json /testnet/dualityd/config/genesis.json

# modify node configuration files
# prevent 'local network address' warning from showing
RUN sed -i 's/addr_book_strict = true/addr_book_strict = false/g' /testnet/dualityd/config/config.toml;
# overwrite CORS rules to allow browser testing and development with frontend local builds
RUN sed -i 's/enabled-unsafe-cors = false/enabled-unsafe-cors = true/g' /testnet/dualityd/config/app.toml;
RUN sed -i 's/cors_allowed_origins = \[\]/cors_allowed_origins = ["*", ]/g' /testnet/dualityd/config/config.toml;
RUN echo '\n\n[rpc]\ncors_allowed_origins = ["*"]' >> /testnet/dualityd/config/app.toml

# see docs for exposed ports:
#   https://docs.ignite.com/kb/config.html#host
EXPOSE 26657
EXPOSE 26656
EXPOSE 6060
EXPOSE 9090
EXPOSE 1317

# default to serving the chain with the modified testnet data
CMD ["dualityd", "--home", "/testnet/dualityd", "start", "--moniker", "duality"]
