// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dex/adj_matrix.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AdjMatrix struct {
	Id      uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EdgeRow *EdgeRow `protobuf:"bytes,2,opt,name=edgeRow,proto3" json:"edgeRow,omitempty"`
}

func (m *AdjMatrix) Reset()         { *m = AdjMatrix{} }
func (m *AdjMatrix) String() string { return proto.CompactTextString(m) }
func (*AdjMatrix) ProtoMessage()    {}
func (*AdjMatrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_664bfcb16bc7ff5c, []int{0}
}
func (m *AdjMatrix) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdjMatrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdjMatrix.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdjMatrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdjMatrix.Merge(m, src)
}
func (m *AdjMatrix) XXX_Size() int {
	return m.Size()
}
func (m *AdjMatrix) XXX_DiscardUnknown() {
	xxx_messageInfo_AdjMatrix.DiscardUnknown(m)
}

var xxx_messageInfo_AdjMatrix proto.InternalMessageInfo

func (m *AdjMatrix) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdjMatrix) GetEdgeRow() *EdgeRow {
	if m != nil {
		return m.EdgeRow
	}
	return nil
}

func init() {
	proto.RegisterType((*AdjMatrix)(nil), "nicholasdotsol.duality.dex.AdjMatrix")
}

func init() { proto.RegisterFile("dex/adj_matrix.proto", fileDescriptor_664bfcb16bc7ff5c) }

var fileDescriptor_664bfcb16bc7ff5c = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x49, 0xad, 0xd0,
	0x4f, 0x4c, 0xc9, 0x8a, 0xcf, 0x4d, 0x2c, 0x29, 0xca, 0xac, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x92, 0xca, 0xcb, 0x4c, 0xce, 0xc8, 0xcf, 0x49, 0x2c, 0x4e, 0xc9, 0x2f, 0x29, 0xce, 0xcf,
	0xd1, 0x4b, 0x29, 0x4d, 0xcc, 0xc9, 0x2c, 0xa9, 0xd4, 0x4b, 0x49, 0xad, 0x90, 0x12, 0x02, 0xe9,
	0x48, 0x4d, 0x49, 0x4f, 0x8d, 0x2f, 0xca, 0x2f, 0x87, 0xa8, 0x57, 0x8a, 0xe2, 0xe2, 0x74, 0x4c,
	0xc9, 0xf2, 0x05, 0x1b, 0x21, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x12, 0xc4, 0x94, 0x99, 0x22, 0x64, 0xcb, 0xc5, 0x0e, 0x52, 0x1e, 0x94, 0x5f, 0x2e, 0xc1, 0xa4,
	0xc0, 0xa8, 0xc1, 0x6d, 0xa4, 0xac, 0x87, 0xdb, 0x78, 0x3d, 0x57, 0x88, 0xd2, 0x20, 0x98, 0x1e,
	0x27, 0xf7, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2,
	0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0xd2, 0x4d, 0xcf, 0x2c,
	0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xf7, 0x83, 0x9a, 0xe8, 0x92, 0x5f, 0x12, 0x9c,
	0x9f, 0xa3, 0x0f, 0x35, 0x51, 0xbf, 0x42, 0x1f, 0xe4, 0xda, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24,
	0x36, 0xb0, 0x5b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x6d, 0xf2, 0xec, 0xf3, 0x00,
	0x00, 0x00,
}

func (m *AdjMatrix) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdjMatrix) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdjMatrix) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EdgeRow != nil {
		{
			size, err := m.EdgeRow.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAdjMatrix(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintAdjMatrix(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAdjMatrix(dAtA []byte, offset int, v uint64) int {
	offset -= sovAdjMatrix(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AdjMatrix) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovAdjMatrix(uint64(m.Id))
	}
	if m.EdgeRow != nil {
		l = m.EdgeRow.Size()
		n += 1 + l + sovAdjMatrix(uint64(l))
	}
	return n
}

func sovAdjMatrix(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAdjMatrix(x uint64) (n int) {
	return sovAdjMatrix(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AdjMatrix) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdjMatrix
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdjMatrix: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdjMatrix: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdjMatrix
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EdgeRow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdjMatrix
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdjMatrix
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdjMatrix
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EdgeRow == nil {
				m.EdgeRow = &EdgeRow{}
			}
			if err := m.EdgeRow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAdjMatrix(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdjMatrix
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAdjMatrix(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAdjMatrix
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAdjMatrix
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAdjMatrix
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAdjMatrix
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAdjMatrix
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAdjMatrix
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAdjMatrix        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAdjMatrix          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAdjMatrix = fmt.Errorf("proto: unexpected end of group")
)
