// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dex/limit_order_pool_total_shares_map.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LimitOrderTrancheTotalSharesMap struct {
	PairId      string                                 `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	Token       string                                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	TickIndex   int64                                  `protobuf:"varint,3,opt,name=tickIndex,proto3" json:"tickIndex,omitempty"`
	Count       uint64                                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	TotalShares github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=totalShares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"totalShares" yaml:"totalShares"`
}

func (m *LimitOrderTrancheTotalSharesMap) Reset()         { *m = LimitOrderTrancheTotalSharesMap{} }
func (m *LimitOrderTrancheTotalSharesMap) String() string { return proto.CompactTextString(m) }
func (*LimitOrderTrancheTotalSharesMap) ProtoMessage()    {}
func (*LimitOrderTrancheTotalSharesMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_da0d15e5c08e1bd4, []int{0}
}
func (m *LimitOrderTrancheTotalSharesMap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LimitOrderTrancheTotalSharesMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LimitOrderTrancheTotalSharesMap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LimitOrderTrancheTotalSharesMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitOrderTrancheTotalSharesMap.Merge(m, src)
}
func (m *LimitOrderTrancheTotalSharesMap) XXX_Size() int {
	return m.Size()
}
func (m *LimitOrderTrancheTotalSharesMap) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitOrderTrancheTotalSharesMap.DiscardUnknown(m)
}

var xxx_messageInfo_LimitOrderTrancheTotalSharesMap proto.InternalMessageInfo

func (m *LimitOrderTrancheTotalSharesMap) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *LimitOrderTrancheTotalSharesMap) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LimitOrderTrancheTotalSharesMap) GetTickIndex() int64 {
	if m != nil {
		return m.TickIndex
	}
	return 0
}

func (m *LimitOrderTrancheTotalSharesMap) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*LimitOrderTrancheTotalSharesMap)(nil), "nicholasdotsol.duality.dex.LimitOrderTrancheTotalSharesMap")
}

func init() {
	proto.RegisterFile("dex/limit_order_pool_total_shares_map.proto", fileDescriptor_da0d15e5c08e1bd4)
}

var fileDescriptor_da0d15e5c08e1bd4 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x3d, 0x6b, 0xf3, 0x30,
	0x14, 0x85, 0xad, 0x37, 0x1f, 0x10, 0xbf, 0x9b, 0x09, 0xc5, 0x84, 0x60, 0x87, 0x0c, 0x25, 0x50,
	0x62, 0x0f, 0xdd, 0x3a, 0x86, 0x40, 0x09, 0xf4, 0x0b, 0xa7, 0x53, 0x17, 0xa3, 0x58, 0x22, 0x11,
	0x91, 0x7d, 0x8d, 0x75, 0x0d, 0xce, 0xbf, 0xe8, 0xcf, 0xca, 0x98, 0xb1, 0x74, 0x30, 0x25, 0xd9,
	0x3a, 0x76, 0xe9, 0x5a, 0xe4, 0x18, 0xe2, 0x49, 0x3a, 0x87, 0x7b, 0x9f, 0x03, 0xe7, 0x9a, 0x37,
	0x8c, 0x17, 0xbe, 0x14, 0xb1, 0xc0, 0x10, 0x32, 0xc6, 0xb3, 0x30, 0x05, 0x90, 0x21, 0x02, 0x52,
	0x19, 0xaa, 0x0d, 0xcd, 0xb8, 0x0a, 0x63, 0x9a, 0x7a, 0x69, 0x06, 0x08, 0xd6, 0x20, 0x11, 0xd1,
	0x06, 0x24, 0x55, 0x0c, 0x50, 0x81, 0xf4, 0x58, 0x4e, 0xa5, 0xc0, 0x9d, 0xc7, 0x78, 0x31, 0xe8,
	0xaf, 0x61, 0x0d, 0xd5, 0x98, 0xaf, 0x7f, 0xe7, 0x8d, 0xf1, 0x2f, 0x31, 0x87, 0x0f, 0x9a, 0xfe,
	0xac, 0xe1, 0x2f, 0x00, 0xf2, 0x55, 0xa3, 0x97, 0x15, 0xf9, 0x91, 0xa6, 0xd6, 0x95, 0xd9, 0x4d,
	0xa9, 0xc8, 0x16, 0xcc, 0x26, 0x23, 0x32, 0xe9, 0x05, 0xb5, 0xb2, 0xfa, 0x66, 0x07, 0x61, 0xcb,
	0x13, 0xfb, 0x5f, 0x65, 0x9f, 0x85, 0x35, 0x34, 0x7b, 0x28, 0xa2, 0xed, 0x22, 0x61, 0xbc, 0xb0,
	0x5b, 0x23, 0x32, 0x69, 0x05, 0x17, 0x43, 0xef, 0x44, 0x90, 0x27, 0x68, 0xb7, 0x47, 0x64, 0xd2,
	0x0e, 0xce, 0xc2, 0xca, 0xcd, 0xff, 0x78, 0xc9, 0xb4, 0x3b, 0x9a, 0x37, 0x5b, 0xee, 0x4b, 0xd7,
	0xf8, 0x2c, 0xdd, 0xeb, 0xb5, 0xc0, 0x4d, 0xbe, 0xf2, 0x22, 0x88, 0xfd, 0x08, 0x54, 0x0c, 0xaa,
	0x7e, 0xa6, 0x8a, 0x6d, 0x7d, 0xdc, 0xa5, 0x5c, 0x79, 0x73, 0x1e, 0x7d, 0x97, 0x6e, 0x13, 0xf2,
	0x53, 0xba, 0xd6, 0x8e, 0xc6, 0xf2, 0x6e, 0xdc, 0x30, 0xc7, 0x41, 0x73, 0x64, 0x76, 0xbf, 0x3f,
	0x3a, 0xe4, 0x70, 0x74, 0xc8, 0xd7, 0xd1, 0x21, 0xef, 0x27, 0xc7, 0x38, 0x9c, 0x1c, 0xe3, 0xe3,
	0xe4, 0x18, 0x6f, 0xd3, 0x46, 0xe6, 0x53, 0x5d, 0xe8, 0x1c, 0x70, 0x09, 0xd2, 0xaf, 0x0b, 0xf5,
	0x0b, 0x5f, 0x9f, 0xa5, 0x8a, 0x5f, 0x75, 0xab, 0x26, 0x6f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x2b, 0x30, 0x26, 0xeb, 0xaa, 0x01, 0x00, 0x00,
}

func (m *LimitOrderTrancheTotalSharesMap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LimitOrderTrancheTotalSharesMap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LimitOrderTrancheTotalSharesMap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalShares.Size()
		i -= size
		if _, err := m.TotalShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLimitOrderTrancheTotalSharesMap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Count != 0 {
		i = encodeVarintLimitOrderTrancheTotalSharesMap(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x20
	}
	if m.TickIndex != 0 {
		i = encodeVarintLimitOrderTrancheTotalSharesMap(dAtA, i, uint64(m.TickIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintLimitOrderTrancheTotalSharesMap(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PairId) > 0 {
		i -= len(m.PairId)
		copy(dAtA[i:], m.PairId)
		i = encodeVarintLimitOrderTrancheTotalSharesMap(dAtA, i, uint64(len(m.PairId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLimitOrderTrancheTotalSharesMap(dAtA []byte, offset int, v uint64) int {
	offset -= sovLimitOrderTrancheTotalSharesMap(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LimitOrderTrancheTotalSharesMap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PairId)
	if l > 0 {
		n += 1 + l + sovLimitOrderTrancheTotalSharesMap(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovLimitOrderTrancheTotalSharesMap(uint64(l))
	}
	if m.TickIndex != 0 {
		n += 1 + sovLimitOrderTrancheTotalSharesMap(uint64(m.TickIndex))
	}
	if m.Count != 0 {
		n += 1 + sovLimitOrderTrancheTotalSharesMap(uint64(m.Count))
	}
	l = m.TotalShares.Size()
	n += 1 + l + sovLimitOrderTrancheTotalSharesMap(uint64(l))
	return n
}

func sovLimitOrderTrancheTotalSharesMap(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLimitOrderTrancheTotalSharesMap(x uint64) (n int) {
	return sovLimitOrderTrancheTotalSharesMap(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LimitOrderTrancheTotalSharesMap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLimitOrderTrancheTotalSharesMap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LimitOrderTrancheTotalSharesMap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LimitOrderTrancheTotalSharesMap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimitOrderTrancheTotalSharesMap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLimitOrderTrancheTotalSharesMap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLimitOrderTrancheTotalSharesMap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PairId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimitOrderTrancheTotalSharesMap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLimitOrderTrancheTotalSharesMap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLimitOrderTrancheTotalSharesMap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TickIndex", wireType)
			}
			m.TickIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimitOrderTrancheTotalSharesMap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TickIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimitOrderTrancheTotalSharesMap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimitOrderTrancheTotalSharesMap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLimitOrderTrancheTotalSharesMap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLimitOrderTrancheTotalSharesMap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLimitOrderTrancheTotalSharesMap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLimitOrderTrancheTotalSharesMap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLimitOrderTrancheTotalSharesMap(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLimitOrderTrancheTotalSharesMap
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLimitOrderTrancheTotalSharesMap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLimitOrderTrancheTotalSharesMap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLimitOrderTrancheTotalSharesMap
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLimitOrderTrancheTotalSharesMap
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLimitOrderTrancheTotalSharesMap
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLimitOrderTrancheTotalSharesMap        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLimitOrderTrancheTotalSharesMap          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLimitOrderTrancheTotalSharesMap = fmt.Errorf("proto: unexpected end of group")
)
