// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dex/order_params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OrderParams struct {
	OrderRule   string                                 `protobuf:"bytes,1,opt,name=orderRule,proto3" json:"orderRule,omitempty"`
	OrderType   uint64                                 `protobuf:"varint,2,opt,name=orderType,proto3" json:"orderType,omitempty"`
	OrderShares github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=orderShares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"orderShares" yaml:"orderShares"`
}

func (m *OrderParams) Reset()         { *m = OrderParams{} }
func (m *OrderParams) String() string { return proto.CompactTextString(m) }
func (*OrderParams) ProtoMessage()    {}
func (*OrderParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cc616f28cd41fb1, []int{0}
}
func (m *OrderParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrderParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrderParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrderParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderParams.Merge(m, src)
}
func (m *OrderParams) XXX_Size() int {
	return m.Size()
}
func (m *OrderParams) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderParams.DiscardUnknown(m)
}

var xxx_messageInfo_OrderParams proto.InternalMessageInfo

func (m *OrderParams) GetOrderRule() string {
	if m != nil {
		return m.OrderRule
	}
	return ""
}

func (m *OrderParams) GetOrderType() uint64 {
	if m != nil {
		return m.OrderType
	}
	return 0
}

func init() {
	proto.RegisterType((*OrderParams)(nil), "nicholasdotsol.duality.dex.OrderParams")
}

func init() { proto.RegisterFile("dex/order_params.proto", fileDescriptor_3cc616f28cd41fb1) }

var fileDescriptor_3cc616f28cd41fb1 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x49, 0xad, 0xd0,
	0xcf, 0x2f, 0x4a, 0x49, 0x2d, 0x8a, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x92, 0xca, 0xcb, 0x4c, 0xce, 0xc8, 0xcf, 0x49, 0x2c, 0x4e, 0xc9, 0x2f, 0x29,
	0xce, 0xcf, 0xd1, 0x4b, 0x29, 0x4d, 0xcc, 0xc9, 0x2c, 0xa9, 0xd4, 0x4b, 0x49, 0xad, 0x90, 0x12,
	0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x2b, 0xd3, 0x07, 0xb1, 0x20, 0x3a, 0x94, 0x0e, 0x30, 0x72, 0x71,
	0xfb, 0x83, 0x0c, 0x0a, 0x00, 0x9b, 0x23, 0x24, 0xc3, 0xc5, 0x09, 0x36, 0x37, 0xa8, 0x34, 0x27,
	0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0x21, 0x00, 0x97, 0x0d, 0xa9, 0x2c, 0x48, 0x95,
	0x60, 0x52, 0x60, 0xd4, 0x60, 0x09, 0x42, 0x08, 0x08, 0x95, 0x72, 0x71, 0x83, 0x39, 0xc1, 0x19,
	0x89, 0x45, 0xa9, 0xc5, 0x12, 0xcc, 0x20, 0xdd, 0x4e, 0xc1, 0x27, 0xee, 0xc9, 0x33, 0xdc, 0xba,
	0x27, 0xaf, 0x96, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9c, 0x5f,
	0x9c, 0x9b, 0x5f, 0x0c, 0xa5, 0x74, 0x8b, 0x53, 0xb2, 0xf5, 0x4b, 0x2a, 0x0b, 0x52, 0x8b, 0xf5,
	0x5c, 0x52, 0x93, 0x5f, 0xdd, 0x93, 0x47, 0x36, 0xe4, 0xd3, 0x3d, 0x79, 0xa1, 0xca, 0xc4, 0xdc,
	0x1c, 0x2b, 0x25, 0x24, 0x41, 0xa5, 0x20, 0x64, 0x25, 0x4e, 0xee, 0x27, 0x1e, 0xc9, 0x31, 0x5e,
	0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31,
	0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xa5, 0x8b, 0x64, 0xa7, 0x1f, 0x34, 0x64, 0x5c, 0xf2, 0x4b, 0x82,
	0xf3, 0x73, 0xf4, 0xa1, 0x21, 0xa3, 0x5f, 0xa1, 0x0f, 0x0a, 0x4a, 0xb0, 0xf5, 0x49, 0x6c, 0xe0,
	0x20, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x95, 0x7b, 0x98, 0x9c, 0x5e, 0x01, 0x00, 0x00,
}

func (m *OrderParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrderParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.OrderShares.Size()
		i -= size
		if _, err := m.OrderShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintOrderParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.OrderType != 0 {
		i = encodeVarintOrderParams(dAtA, i, uint64(m.OrderType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OrderRule) > 0 {
		i -= len(m.OrderRule)
		copy(dAtA[i:], m.OrderRule)
		i = encodeVarintOrderParams(dAtA, i, uint64(len(m.OrderRule)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintOrderParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovOrderParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OrderParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderRule)
	if l > 0 {
		n += 1 + l + sovOrderParams(uint64(l))
	}
	if m.OrderType != 0 {
		n += 1 + sovOrderParams(uint64(m.OrderType))
	}
	l = m.OrderShares.Size()
	n += 1 + l + sovOrderParams(uint64(l))
	return n
}

func sovOrderParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOrderParams(x uint64) (n int) {
	return sovOrderParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OrderParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderRule", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrderParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderRule = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderType", wireType)
			}
			m.OrderType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderType |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOrderParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OrderShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrderParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOrderParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOrderParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrderParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrderParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOrderParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOrderParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOrderParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOrderParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOrderParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOrderParams = fmt.Errorf("proto: unexpected end of group")
)
