// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dex/shares.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Shares struct {
	Address     string                                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Price       string                                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Fee         string                                 `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	OrderType   string                                 `protobuf:"bytes,4,opt,name=orderType,proto3" json:"orderType,omitempty"`
	SharesOwned github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=sharesOwned,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"sharesOwned" yaml:"sharesOwned"`
}

func (m *Shares) Reset()         { *m = Shares{} }
func (m *Shares) String() string { return proto.CompactTextString(m) }
func (*Shares) ProtoMessage()    {}
func (*Shares) Descriptor() ([]byte, []int) {
	return fileDescriptor_a718b920552bb586, []int{0}
}
func (m *Shares) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Shares) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Shares.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Shares) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shares.Merge(m, src)
}
func (m *Shares) XXX_Size() int {
	return m.Size()
}
func (m *Shares) XXX_DiscardUnknown() {
	xxx_messageInfo_Shares.DiscardUnknown(m)
}

var xxx_messageInfo_Shares proto.InternalMessageInfo

func (m *Shares) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Shares) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Shares) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *Shares) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func init() {
	proto.RegisterType((*Shares)(nil), "nicholasdotsol.duality.dex.Shares")
}

func init() { proto.RegisterFile("dex/shares.proto", fileDescriptor_a718b920552bb586) }

var fileDescriptor_a718b920552bb586 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0x4a, 0x8b, 0x6a, 0x96, 0xca, 0xea, 0x60, 0x55, 0xc8, 0x41, 0x1d, 0x10, 0x4b,
	0xe3, 0x81, 0x8d, 0xb1, 0xaa, 0xc4, 0x06, 0x52, 0xcb, 0xc4, 0x96, 0xc6, 0x47, 0x1b, 0x91, 0xf6,
	0x22, 0xdb, 0x15, 0xcd, 0x5b, 0xf0, 0x58, 0x1d, 0x3b, 0x22, 0x86, 0x80, 0x92, 0x8d, 0x91, 0x27,
	0x40, 0x71, 0x82, 0xc8, 0xe4, 0xbb, 0xcf, 0xe7, 0xfb, 0xad, 0x8f, 0x0e, 0x14, 0xec, 0xa5, 0x59,
	0x87, 0x1a, 0x4c, 0x90, 0x6a, 0xb4, 0xc8, 0x46, 0xdb, 0x38, 0x5a, 0x63, 0x12, 0x1a, 0x85, 0xd6,
	0x60, 0x12, 0xa8, 0x5d, 0x98, 0xc4, 0x36, 0x0b, 0x14, 0xec, 0x47, 0xc3, 0x15, 0xae, 0xd0, 0x8d,
	0xc9, 0xaa, 0xaa, 0x5f, 0x8c, 0x3f, 0x09, 0xed, 0x2d, 0xdc, 0x0a, 0xc6, 0xe9, 0x59, 0xa8, 0x94,
	0x06, 0x63, 0x38, 0xb9, 0x24, 0xd7, 0xfd, 0xf9, 0x5f, 0xcb, 0x86, 0xb4, 0x9b, 0xea, 0x38, 0x02,
	0x7e, 0xe2, 0x78, 0xdd, 0xb0, 0x01, 0xed, 0x3c, 0x03, 0xf0, 0x8e, 0x63, 0x55, 0xc9, 0x2e, 0x68,
	0x1f, 0xb5, 0x02, 0xfd, 0x98, 0xa5, 0xc0, 0x4f, 0x1d, 0xff, 0x07, 0x6c, 0x47, 0xcf, 0xeb, 0xcf,
	0x3e, 0xbc, 0x6e, 0x41, 0xf1, 0x6e, 0x75, 0x3f, 0x5d, 0x1c, 0x72, 0xdf, 0xfb, 0xc8, 0xfd, 0xab,
	0x55, 0x6c, 0xd7, 0xbb, 0x65, 0x10, 0xe1, 0x46, 0x46, 0x68, 0x36, 0x68, 0x9a, 0x63, 0x62, 0xd4,
	0x8b, 0xb4, 0x59, 0x0a, 0x26, 0x98, 0x41, 0xf4, 0x9d, 0xfb, 0xed, 0x25, 0x3f, 0xb9, 0xcf, 0xb2,
	0x70, 0x93, 0xdc, 0x8e, 0x5b, 0x70, 0x3c, 0x6f, 0x8f, 0x4c, 0xef, 0x0e, 0x85, 0x20, 0xc7, 0x42,
	0x90, 0xaf, 0x42, 0x90, 0xb7, 0x52, 0x78, 0xc7, 0x52, 0x78, 0xef, 0xa5, 0xf0, 0x9e, 0x26, 0xad,
	0xcc, 0xfb, 0x46, 0xdc, 0x0c, 0xed, 0x02, 0x13, 0xd9, 0x88, 0x93, 0x7b, 0x59, 0x39, 0x76, 0xf1,
	0xcb, 0x9e, 0x33, 0x76, 0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xdc, 0x9b, 0x96, 0x77, 0x01,
	0x00, 0x00,
}

func (m *Shares) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Shares) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Shares) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.SharesOwned.Size()
		i -= size
		if _, err := m.SharesOwned.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintShares(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.OrderType) > 0 {
		i -= len(m.OrderType)
		copy(dAtA[i:], m.OrderType)
		i = encodeVarintShares(dAtA, i, uint64(len(m.OrderType)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintShares(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintShares(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintShares(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintShares(dAtA []byte, offset int, v uint64) int {
	offset -= sovShares(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Shares) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovShares(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovShares(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovShares(uint64(l))
	}
	l = len(m.OrderType)
	if l > 0 {
		n += 1 + l + sovShares(uint64(l))
	}
	l = m.SharesOwned.Size()
	n += 1 + l + sovShares(uint64(l))
	return n
}

func sovShares(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozShares(x uint64) (n int) {
	return sovShares(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Shares) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShares
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Shares: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Shares: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShares
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShares
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShares
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShares
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShares
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShares
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShares
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShares
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SharesOwned", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShares
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShares
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SharesOwned.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShares(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShares
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipShares(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowShares
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShares
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShares
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthShares
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupShares
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthShares
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthShares        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowShares          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupShares = fmt.Errorf("proto: unexpected end of group")
)
