# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tendermint/p2p/types.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import List

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class ProtocolVersion(betterproto.Message):
    p2_p: int = betterproto.uint64_field(1)
    block: int = betterproto.uint64_field(2)
    app: int = betterproto.uint64_field(3)


@dataclass(eq=False, repr=False)
class NodeInfo(betterproto.Message):
    protocol_version: "ProtocolVersion" = betterproto.message_field(1)
    node_id: str = betterproto.string_field(2)
    listen_addr: str = betterproto.string_field(3)
    network: str = betterproto.string_field(4)
    version: str = betterproto.string_field(5)
    channels: bytes = betterproto.bytes_field(6)
    moniker: str = betterproto.string_field(7)
    other: "NodeInfoOther" = betterproto.message_field(8)


@dataclass(eq=False, repr=False)
class NodeInfoOther(betterproto.Message):
    tx_index: str = betterproto.string_field(1)
    rpc_address: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class PeerInfo(betterproto.Message):
    id: str = betterproto.string_field(1)
    address_info: List["PeerAddressInfo"] = betterproto.message_field(2)
    last_connected: datetime = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class PeerAddressInfo(betterproto.Message):
    address: str = betterproto.string_field(1)
    last_dial_success: datetime = betterproto.message_field(2)
    last_dial_failure: datetime = betterproto.message_field(3)
    dial_failures: int = betterproto.uint32_field(4)
