# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/crypto/keyring/v1/record.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class Record(betterproto.Message):
    """Record is used for representing a key in the keyring."""

    # name represents a name of Record
    name: str = betterproto.string_field(1)
    # pub_key represents a public key in any format
    pub_key: "betterproto_lib_google_protobuf.Any" = betterproto.message_field(2)
    # local stores the public information about a locally stored key
    local: "RecordLocal" = betterproto.message_field(3, group="item")
    # ledger stores the public information about a Ledger key
    ledger: "RecordLedger" = betterproto.message_field(4, group="item")
    # Multi does not store any information.
    multi: "RecordMulti" = betterproto.message_field(5, group="item")
    # Offline does not store any information.
    offline: "RecordOffline" = betterproto.message_field(6, group="item")


@dataclass(eq=False, repr=False)
class RecordLocal(betterproto.Message):
    """Item is a keyring item stored in a keyring backend. Local item"""

    priv_key: "betterproto_lib_google_protobuf.Any" = betterproto.message_field(1)
    priv_key_type: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class RecordLedger(betterproto.Message):
    """Ledger item"""

    path: "__hd_v1__.Bip44Params" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class RecordMulti(betterproto.Message):
    """Multi item"""

    pass


@dataclass(eq=False, repr=False)
class RecordOffline(betterproto.Message):
    """Offline item"""

    pass


from ...hd import v1 as __hd_v1__
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf
